name: combine_files

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  combine_files:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Run Python script
        run: python ./.github/workflows/combine.py

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto Commit - Combine Files
